export default interface PoketListResponseDto {
  name : string;
  type : string;
  specificity : string;
  characters : string;
  things : string;
  individualHp : number;
  individualAttack : number;
  individualDefence : number;
  individualSpecialAttack : number;
  individualSpecialDefence : number;
  individualSpeed : number;
  effortHp : number;
  effortAttack : number;
  effortDefence : number;
  effortSpecialAttack : number;
  effortSpecialDefence : number; 
  effortSpeed : number;
  technologyOne : string;
  technologyTwo : string;
  technologyThree : string;
  technologyFour : string;
};